name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.3
  flutter_screenutil: ^5.9.3
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: readexPro
      fonts:


        - asset: fonts/static/ReadexPro-Regular.ttf